-- EJERCICIO 1
SET AUTOCOMMIT=0;
START TRANSACTION;
	DELETE FROM categories
	WHERE id=1;
-- ROLLBACK;
-- COMMIT;
SET AUTOCOMMIT=1;

-- EJERCICIO 2
SET AUTOCOMMIT=0;
START TRANSACTION;
	INSERT INTO sales VALUES (NULL,1,"Carrera 123",1,1,1,1,CURDATE(),NULL,NULL);
    INSERT INTO sales VALUES (NULL,2,"Carrera 123",2,2,2,2,CURDATE(),NULL,NULL);
    INSERT INTO sales VALUES (NULL,3,"Carrera 123",3,3,3,3,CURDATE(),NULL,NULL);
    INSERT INTO sales VALUES (NULL,4,"Carrera 123",4,4,4,4,CURDATE(),NULL,NULL);
    SAVEPOINT primer_lote;
	INSERT INTO sales VALUES (NULL,1,"Carrera 123",1,1,1,1,CURDATE(),NULL,NULL);
    INSERT INTO sales VALUES (NULL,2,"Carrera 123",2,2,2,2,CURDATE(),NULL,NULL);
    INSERT INTO sales VALUES (NULL,3,"Carrera 123",3,3,3,3,CURDATE(),NULL,NULL);
    INSERT INTO sales VALUES (NULL,4,"Carrera 123",4,4,4,4,CURDATE(),NULL,NULL);
    SAVEPOINT segundo_lote;

RELEASE SAVEPOINT primer_lote;
SET AUTOCOMMIT=1;